name: ${project.name}
main: com.projectg.geyserupdater.spigot.SpigotUpdater
version: ${project.version}
depend: [Geyser-Spigot]
description: Automatically or manually downloads new builds of Geyser and applies them on server restart.

commands:
  geyserupdate:
    description: updating Geyser command
    permission: gupdater.geyserupdate
    aliases: /geyserupdate
