name: GeyserUpdater
main: com.alysaa.geyserupdater.spigot.SpigotUpdater
version: ${project.version}
depend: [Geyser-Spigot]
description: Automatically downloads new builds of Geyser and applies them on server restart.

commands:
  geyserupdate:
    description: updating Geyser command
    permission: gupdater.geyserupdate
    aliases: /geyserupdate
